<?php
// Automatically Generated by TestLink Installer - Tue, 09 Apr 24 19:39:46 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '172.22.1.19');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
